create table master.dbo.validation_syntax_15_15 (id int identity(1,1), syntax nvarchar(max))
go
declare @s nvarchar(max) = '
USE [BAB_MIS]
/****** Object:  View [ATM_TRX_STAT]    Script Date: 11/3/2021 9:01:00 AM ******/
GO

CREATE VIEW dbo.[ENJAZ_TRANSACTIONS] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[ENJAZ_TRANSACTIONS] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[ENJAZ_TRANSACTIONS] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[ENJAZ_TRANSACTIONS] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[ENJAZ_TRANSACTIONS] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[ENJAZ_TRANSACTIONS] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[ENJAZ_TRANSACTIONS] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[ENJAZ_TRANSACTIONS] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[ENJAZ_TRANSACTIONS] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[ENJAZ_TRANSACTIONS] 

GO

CREATE VIEW dbo.[ATM_TRX_STAT] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[ATM_TRX_STAT] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[ATM_TRX_STAT] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[ATM_TRX_STAT] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[ATM_TRX_STAT] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[ATM_TRX_STAT] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[ATM_TRX_STAT] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[ATM_TRX_STAT] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[ATM_TRX_STAT] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[ATM_TRX_STAT] 
 
GO



CREATE VIEW dbo.[MIS_ACCOUNT] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[MIS_ACCOUNT] 

GO

CREATE VIEW dbo.[MIS_FT] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[MIS_FT]
 
 
 GO

CREATE VIEW dbo.[MIS_LC] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[MIS_LC]
 
 GO
 
 CREATE VIEW dbo.[MIS_LD] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[MIS_LD]
 
 GO
  
 CREATE VIEW dbo.[MIS_MD] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[MIS_MD]
 
 
 GO

 CREATE VIEW dbo.[MIS_MM] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[MIS_MM]
 
 GO
  
 CREATE VIEW dbo.[MIS_PD] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[MIS_PD]
 
 GO
   
 CREATE VIEW dbo.[MIS_SE] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[MIS_SE]
 
 GO
 
 CREATE VIEW dbo.[MIS_TT] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[MIS_TT]
 
 
 
 GO
 
 CREATE VIEW dbo.[VAT_RETURN_DETAILS] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[VAT_RETURN_DETAILS] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[VAT_RETURN_DETAILS] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[VAT_RETURN_DETAILS] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[VAT_RETURN_DETAILS] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[VAT_RETURN_DETAILS] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[VAT_RETURN_DETAILS] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[VAT_RETURN_DETAILS] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[VAT_RETURN_DETAILS] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[VAT_RETURN_DETAILS]



 
CREATE VIEW dbo.[TMP_MIS_ACCOUNT] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[TMP_MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[TMP_MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[TMP_MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[TMP_MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[TMP_MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[TMP_MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[TMP_MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[TMP_MIS_ACCOUNT] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[TMP_MIS_ACCOUNT] 

GO

CREATE VIEW dbo.[TMP_MIS_FT] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[TMP_MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[TMP_MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[TMP_MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[TMP_MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[TMP_MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[TMP_MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[TMP_MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[TMP_MIS_FT] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[TMP_MIS_FT]
 
 
 GO

CREATE VIEW dbo.[TMP_MIS_LC] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[TMP_MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[TMP_MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[TMP_MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[TMP_MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[TMP_MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[TMP_MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[TMP_MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[TMP_MIS_LC] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[TMP_MIS_LC]
 
 GO
 
 CREATE VIEW dbo.[TMP_MIS_LD] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[TMP_MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[TMP_MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[TMP_MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[TMP_MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[TMP_MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[TMP_MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[TMP_MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[TMP_MIS_LD] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[TMP_MIS_LD]
 
 GO
  
 CREATE VIEW dbo.[TMP_MIS_MD] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[TMP_MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[TMP_MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[TMP_MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[TMP_MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[TMP_MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[TMP_MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[TMP_MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[TMP_MIS_MD] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[TMP_MIS_MD]
 
 
 GO

 CREATE VIEW dbo.[TMP_MIS_MM] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[TMP_MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[TMP_MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[TMP_MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[TMP_MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[TMP_MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[TMP_MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[TMP_MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[TMP_MIS_MM] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[TMP_MIS_MM]
 
 GO
  
 CREATE VIEW dbo.[TMP_MIS_PD] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[TMP_MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[TMP_MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[TMP_MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[TMP_MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[TMP_MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[TMP_MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[TMP_MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[TMP_MIS_PD] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[TMP_MIS_PD]
 
 GO
   
 CREATE VIEW dbo.[TMP_MIS_SE] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[TMP_MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[TMP_MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[TMP_MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[TMP_MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[TMP_MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[TMP_MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[TMP_MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[TMP_MIS_SE] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[TMP_MIS_SE]
 
 GO
 
 CREATE VIEW dbo.[TMP_MIS_TT] AS 
 SELECT * FROM [BAB_MIS_2018].dbo.[TMP_MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2019].dbo.[TMP_MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2020].dbo.[TMP_MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2021].dbo.[TMP_MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2022].dbo.[TMP_MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2023].dbo.[TMP_MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2024].dbo.[TMP_MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_2025].dbo.[TMP_MIS_TT] UNION ALL
 SELECT * FROM [BAB_MIS_Max].dbo.[TMP_MIS_TT]
 
 
 
 GO'

insert into master.dbo.validation_syntax_15_15
select value from master.dbo.Separator(@s,char(10))
order by id

