ALTER AVAILABILITY GROUP T24_XIO MODIFY REPLICA ON 'D1T24DBSQPWV5' 
WITH ( AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT)
go
ALTER AVAILABILITY GROUP T24_XIO MODIFY REPLICA ON 'D2T24DBSQPWV4'  
WITH ( AVAILABILITY_MODE = SYNCHRONOUS_COMMIT)
go
ALTER AVAILABILITY GROUP T24_XIO MODIFY REPLICA ON 'D2T24DBSQPWV5' 
WITH ( AVAILABILITY_MODE = SYNCHRONOUS_COMMIT)

