--CREATE VIEW [dbo].[V_test_xml2] 
--WITH SCHEMABINDING 
--AS
SELECT top 10000 
a.RECID, a.XMLRECORD [THE_RECORD], a.RECID [VISA_CARDS_REFNO],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,1) [ACTION_CODE],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,2) [CARD_NUMBER],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,3) [SUP_CARD_NUMBER],
a.XMLRECORD.query('/row/c3') [SUP_CARD_NUMBER_3],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,5) [CUSTOMER],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,6) [ADD_ON_CUST_NO],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,7) [CURRENCY],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,8) [CUSTOMER_DAO],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,9) [LEGAL_ID],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,10) [EMBOSS_NAME],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,11) [VISA_CRD_TYPE],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,12) [CARD_LIMIT],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,13) [CARD_DEL_ADD],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,14) [LANGUAGE_CODE],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,15) [MAIL_CODE],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,16) [BRANCH_CODE],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,17) [ISSUE_DATE],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,18) [EXPIRY_DATE],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,19) [GENDER],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,20) [SEGMENT],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,21) [CARD_SUB_TYPE],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,22) [ACTIVE_FLAG],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,23) [CARD_STATUS],
[dbo].[FBNK_BAB_VISA_CRD_ISSUE_DYNAMIC_Columns_NVARCHAR](XMLRECORD,24) [REASON_DESC]
--,a.XMLRECORD.query('/row/c24') "REASON_DESC_24"
--,a.XMLRECORD.value('data(/row/c25)[1]', 'nvarchar(max)') "ID_TYPE"
--,a.XMLRECORD.value('data(/row/c26)[1]', 'nvarchar(max)') "ID_EXP_DATE"
--,a.XMLRECORD.value('data(/row/c27)[1]', 'nvarchar(max)') "CUSTOMER_NAME"
--,a.XMLRECORD.query('/row/c27') "CUSTOMER_NAME_27"
--,a.XMLRECORD.value('data(/row/c28)[1]', 'nvarchar(max)') "CUSTOMER_DOB"
--,a.XMLRECORD.value('data(/row/c29)[1]', 'nvarchar(max)') "NATIONALITY"
--,a.XMLRECORD.value('data(/row/c30)[1]', 'nvarchar(max)') "EMAIL"
--,a.XMLRECORD.value('data(/row/c31)[1]', 'nvarchar(max)') "MARITAL_STATUS"
--,a.XMLRECORD.value('data(/row/c32)[1]', 'nvarchar(max)') "MAILING_ADDRESS"
--,a.XMLRECORD.query('/row/c32') "MAILING_ADDRESS_32"
--,a.XMLRECORD.value('data(/row/c33)[1]', 'nvarchar(max)') "EMPLOYMENT_TYPE"
--,a.XMLRECORD.value('data(/row/c34)[1]', 'nvarchar(max)') "WORK_ADDRESS"
--,a.XMLRECORD.query('/row/c34') "WORK_ADDRESS_34"
--,a.XMLRECORD.value('data(/row/c35)[1]', 'nvarchar(max)') "TOTAL_MON_SAL"
--,a.XMLRECORD.value('data(/row/c36)[1]', 'nvarchar(max)') "LN_OTHR_BNK_INST"
--,a.XMLRECORD.value('data(/row/c37)[1]', 'nvarchar(max)') "OTHR_BNK_CRD_LIM"
--,a.XMLRECORD.value('data(/row/c38)[1]', 'nvarchar(max)') "SUP_CRD_CUS_NAME"
--,a.XMLRECORD.value('data(/row/c39)[1]', 'nvarchar(max)') "SUP_CUS_LEGAL_ID"
--,a.XMLRECORD.value('data(/row/c40)[1]', 'nvarchar(max)') "SUP_CUS_ID_EXP_DT"
--,a.XMLRECORD.value('data(/row/c41)[1]', 'nvarchar(max)') "SUP_CUS_DOB"
--,a.XMLRECORD.value('data(/row/c42)[1]', 'nvarchar(max)') "SUP_CUS_GENDER"
--,a.XMLRECORD.value('data(/row/c43)[1]', 'nvarchar(max)') "POS_LIMIT_AMT"
--,a.XMLRECORD.value('data(/row/c44)[1]', 'nvarchar(max)') "CASH_ADV_LIM_AMT"
--,a.XMLRECORD.value('data(/row/c45)[1]', 'nvarchar(max)') "CARD_DESIGN"
--,a.XMLRECORD.value('data(/row/c46)[1]', 'nvarchar(max)') "BULK_EXT_FILE_Y_N"
--,a.XMLRECORD.value('data(/row/c47)[1]', 'nvarchar(max)') "BULK_MNT_FILE_Y_N"
--,a.XMLRECORD.value('data(/row/c48)[1]', 'nvarchar(max)') "CARD_ISS_COMPLETE"
--,a.XMLRECORD.value('data(/row/c49)[1]', 'nvarchar(max)') "CARD_ISS_REJECTED"
--,a.XMLRECORD.value('data(/row/c50)[1]', 'nvarchar(max)') "CMS_INT_ACCT_NO"
--,a.XMLRECORD.value('data(/row/c51)[1]', 'nvarchar(max)') "CARD_AC_CLASS"
--,a.XMLRECORD.value('data(/row/c52)[1]', 'nvarchar(max)') "BULK_CUS_MNT_FILE_Y_N"
--,a.XMLRECORD.value('data(/row/c53)[1]', 'nvarchar(max)') "CUS_ID_EXP_FILE_Y_N"
--,a.XMLRECORD.value('data(/row/c54)[1]', 'nvarchar(max)') "SIMAH_CLOSE_STATUS_REP_DATE"
--,a.XMLRECORD.value('data(/row/c55)[1]', 'nvarchar(max)') "CMS_CN_RN"
--,a.XMLRECORD.value('data(/row/c56)[1]', 'nvarchar(max)') "PRIM_ISS_ID"
--,a.XMLRECORD.value('data(/row/c57)[1]', 'nvarchar(max)') "TEMP_EMBOSS_NAME"
--,a.XMLRECORD.value('data(/row/c58)[1]', 'nvarchar(max)') "T24_UNIQUE_ID"
--,a.XMLRECORD.value('data(/row/c59)[1]', 'nvarchar(max)') "T24_OLD_UNIQUE_ID"
--,a.XMLRECORD.query('/row/c59') "T24_OLD_UNIQUE_ID_59"
--,a.XMLRECORD.value('data(/row/c60)[1]', 'nvarchar(max)') "REPLACEMENT_DATE"
--,a.XMLRECORD.value('data(/row/c61)[1]', 'nvarchar(max)') "CMS_ID"
--,a.XMLRECORD.value('data(/row/c62)[1]', 'nvarchar(max)') "CMS_ACCT_STATUS"
--,a.XMLRECORD.value('data(/row/c63)[1]', 'nvarchar(max)') "CMSRN_REPL"
--,a.XMLRECORD.value('data(/row/c64)[1]', 'nvarchar(max)') "SELL_STAFF_ID"
--,a.XMLRECORD.value('data(/row/c65)[1]', 'nvarchar(max)') "SELL_STAFF_BRANCH"
--,a.XMLRECORD.value('data(/row/c66)[1]', 'nvarchar(max)') "CRD_IS_CHRGS"
--,a.XMLRECORD.value('data(/row/c67)[1]', 'nvarchar(max)') "DELIVERY_BRANCH"
--,a.XMLRECORD.value('data(/row/c68)[1]', 'nvarchar(max)') "CTX_PRODUCT"
--,a.XMLRECORD.value('data(/row/c69)[1]', 'nvarchar(max)') "CMS_PRIM_SUP"
--,a.XMLRECORD.value('data(/row/c70)[1]', 'nvarchar(max)') "PRIMARY_CARD_LIMIT"
--,a.XMLRECORD.value('data(/row/c71)[1]', 'nvarchar(max)') "RENEWAL_DATE"
--,a.XMLRECORD.value('data(/row/c72)[1]', 'nvarchar(max)') "REV_CARD_RENEW"
--,a.XMLRECORD.value('data(/row/c73)[1]', 'nvarchar(max)') "BUSINESS_PROD"
--,a.XMLRECORD.value('data(/row/c74)[1]', 'nvarchar(max)') "GENERIC"
--,a.XMLRECORD.value('data(/row/c75)[1]', 'nvarchar(max)') "FT_REFERENCE"
--,a.XMLRECORD.value('data(/row/c76)[1]', 'nvarchar(max)') "REPL_REASON"
--,a.XMLRECORD.value('data(/row/c77)[1]', 'nvarchar(max)') "SAL_ASSIGNMENT"
--,a.XMLRECORD.value('data(/row/c78)[1]', 'nvarchar(max)') "SAL_APPROVED_EMPLOYER"
--,a.XMLRECORD.value('data(/row/c79)[1]', 'nvarchar(max)') "NON_SAL_TYPE"
--,a.XMLRECORD.value('data(/row/c80)[1]', 'nvarchar(max)') "EXCEPTION_Y_N"
--,a.XMLRECORD.value('data(/row/c81)[1]', 'nvarchar(max)') "EXCEPT_REASON"
--,a.XMLRECORD.value('data(/row/c82)[1]', 'nvarchar(max)') "EXCEPT_NOTES"
--,a.XMLRECORD.query('/row/c82') "EXCEPT_NOTES_82"
--,a.XMLRECORD.value('data(/row/c83)[1]', 'nvarchar(max)') "EXCEPT_APP_AUTH"
--,a.XMLRECORD.value('data(/row/c84)[1]', 'nvarchar(max)') "DECISION"
--,a.XMLRECORD.value('data(/row/c85)[1]', 'nvarchar(max)') "REJECT_REASON"
--,a.XMLRECORD.query('/row/c85') "REJECT_REASON_85"
--,a.XMLRECORD.value('data(/row/c86)[1]', 'nvarchar(max)') "DESCRIPTION"
--,a.XMLRECORD.query('/row/c86') "DESCRIPTION_86"
--,a.XMLRECORD.value('data(/row/c87)[1]', 'nvarchar(max)') "EMPLOYEE_Y_N"
--,a.XMLRECORD.value('data(/row/c88)[1]', 'nvarchar(max)') "EMPLOYER"
--,a.XMLRECORD.value('data(/row/c89)[1]', 'nvarchar(max)') "OCCUPATION"
--,a.XMLRECORD.value('data(/row/c90)[1]', 'nvarchar(max)') "DEPARTMENT"
--,a.XMLRECORD.value('data(/row/c91)[1]', 'nvarchar(max)') "SALARY"
--,a.XMLRECORD.value('data(/row/c92)[1]', 'nvarchar(max)') "REMARKS"
--,a.XMLRECORD.query('/row/c92') "REMARKS_92"
--,a.XMLRECORD.value('data(/row/c93)[1]', 'nvarchar(max)') "CARD_TYPE"
--,a.XMLRECORD.value('data(/row/c94)[1]', 'nvarchar(max)') "REQ_STATUS"
--,a.XMLRECORD.value('data(/row/c95)[1]', 'nvarchar(max)') "APPLCNT_ID"
--,a.XMLRECORD.value('data(/row/c96)[1]', 'nvarchar(max)') "CHANNEL_REF"
--,a.XMLRECORD.value('data(/row/c97)[1]', 'nvarchar(max)') "CMSRN_PRIM"
--,a.XMLRECORD.value('data(/row/c98)[1]', 'nvarchar(max)') "SIMAH_REF"
--,a.XMLRECORD.query('/row/c98') "SIMAH_REF_98"
--,a.XMLRECORD.value('data(/row/c99)[1]', 'nvarchar(max)') "SIMAH_RESPONSE"
--,a.XMLRECORD.query('/row/c99') "SIMAH_RESPONSE_99"
--,a.XMLRECORD.value('data(/row/c100)[1]', 'nvarchar(max)') "PREV_CMS_REF"
--,a.XMLRECORD.query('/row/c100') "PREV_CMS_REF_100"
--,a.XMLRECORD.value('data(/row/c101)[1]', 'nvarchar(max)') "BHVR_ALIGNMENT_SCORE"
--,a.XMLRECORD.query('/row/c101') "BHVR_ALIGNMENT_SCORE_101"
--,a.XMLRECORD.value('data(/row/c102)[1]', 'nvarchar(max)') "BHVR_FINAL_DECISION"
--,a.XMLRECORD.query('/row/c102') "BHVR_FINAL_DECISION_102"
--,a.XMLRECORD.value('data(/row/c103)[1]', 'nvarchar(max)') "APPL_ALIGNMENT_SCORE"
--,a.XMLRECORD.value('data(/row/c104)[1]', 'nvarchar(max)') "APPL_FINAL_DECISION"
--,a.XMLRECORD.value('data(/row/c105)[1]', 'nvarchar(max)') "EMP_JOIN_DATE"
--,a.XMLRECORD.value('data(/row/c106)[1]', 'nvarchar(max)') "CMS_ACCT_LIMIT"
--,a.XMLRECORD.value('data(/row/c107)[1]', 'nvarchar(max)') "CMS_CRD_LIMIT"
--,a.XMLRECORD.value('data(/row/c108)[1]', 'nvarchar(max)') "AVG_BAL_AMNT"
--,a.XMLRECORD.value('data(/row/c109)[1]', 'nvarchar(max)') "LIEN_AMNT"
--,a.XMLRECORD.value('data(/row/c110)[1]', 'nvarchar(max)') "CORP_CUST"
--,a.XMLRECORD.value('data(/row/c111)[1]', 'nvarchar(max)') "REQ_USR_ID"
--,a.XMLRECORD.value('data(/row/c112)[1]', 'nvarchar(max)') "REQ_ACT"
--,a.XMLRECORD.value('data(/row/c113)[1]', 'nvarchar(max)') "SRV_ID"
--,a.XMLRECORD.value('data(/row/c114)[1]', 'nvarchar(max)') "LAST_USR_ID"
--,a.XMLRECORD.query('/row/c114') "LAST_USR_ID_114"
--,a.XMLRECORD.value('data(/row/c115)[1]', 'nvarchar(max)') "LAST_ACT_TS"
--,a.XMLRECORD.query('/row/c115') "LAST_ACT_TS_115"
--,a.XMLRECORD.value('data(/row/c116)[1]', 'nvarchar(max)') "LAST_USR_LVL"
--,a.XMLRECORD.query('/row/c116') "LAST_USR_LVL_116"
--,a.XMLRECORD.value('data(/row/c117)[1]', 'nvarchar(max)') "PREV_LIMIT"
--,a.XMLRECORD.value('data(/row/c118)[1]', 'nvarchar(max)') "REM_GLOBAL_LIMIT"
--,a.XMLRECORD.value('data(/row/c119)[1]', 'nvarchar(max)') "ALLOWED_CCY"
--,a.XMLRECORD.query('/row/c119') "ALLOWED_CCY_119"
--,a.XMLRECORD.value('data(/row/c120)[1]', 'nvarchar(max)') "INCOMP_REASON_CODE"
--,a.XMLRECORD.value('data(/row/c121)[1]', 'nvarchar(max)') "NON_SAL_TYPE_LIMIT"
--,a.XMLRECORD.query('/row/c121') "NON_SAL_TYPE_LIMIT_121"
--,a.XMLRECORD.value('data(/row/c122)[1]', 'nvarchar(max)') "SEND_OTP"
--,a.XMLRECORD.value('data(/row/c123)[1]', 'nvarchar(max)') "VALIDATE_OTP"
--,a.XMLRECORD.value('data(/row/c124)[1]', 'nvarchar(max)') "HER_SAL_TRNSFR_PRG"
--,a.XMLRECORD.value('data(/row/c125)[1]', 'nvarchar(max)') "OTHER_INCOME_TYPE"
--,a.XMLRECORD.query('/row/c125') "OTHER_INCOME_TYPE_125"
--,a.XMLRECORD.value('data(/row/c126)[1]', 'nvarchar(max)') "OTHER_INCOME_FREQ"
--,a.XMLRECORD.query('/row/c126') "OTHER_INCOME_FREQ_126"
--,a.XMLRECORD.value('data(/row/c127)[1]', 'nvarchar(max)') "OTHER_INCOME_AMT"
--,a.XMLRECORD.query('/row/c127') "OTHER_INCOME_AMT_127"
--,a.XMLRECORD.value('data(/row/c128)[1]', 'nvarchar(max)') "EXPENSE_TYPE"
--,a.XMLRECORD.query('/row/c128') "EXPENSE_TYPE_128"
--,a.XMLRECORD.value('data(/row/c129)[1]', 'nvarchar(max)') "EXPENSE_FREQ"
--,a.XMLRECORD.query('/row/c129') "EXPENSE_FREQ_129"
--,a.XMLRECORD.value('data(/row/c130)[1]', 'nvarchar(max)') "EXPENSE_AMT"
--,a.XMLRECORD.query('/row/c130') "EXPENSE_AMT_130"
--,a.XMLRECORD.value('data(/row/c131)[1]', 'nvarchar(max)') "EXPENSE_MTH_AMT"
--,a.XMLRECORD.query('/row/c131') "EXPENSE_MTH_AMT_131"
--,a.XMLRECORD.value('data(/row/c132)[1]', 'nvarchar(max)') "TOT_CUS_EXPENSES"
--,a.XMLRECORD.value('data(/row/c133)[1]', 'nvarchar(max)') "TOT_OTH_INCOME"
--,a.XMLRECORD.value('data(/row/c134)[1]', 'nvarchar(max)') "PROD_CODE"
--,a.XMLRECORD.value('data(/row/c135)[1]', 'nvarchar(max)') "REQ_BRANCH"
--,a.XMLRECORD.value('data(/row/c136)[1]', 'nvarchar(max)') "ELIGIBLE_CARD_LIMIT"
--,a.XMLRECORD.value('data(/row/c137)[1]', 'nvarchar(max)') "PLASTIC"
--,a.XMLRECORD.value('data(/row/c138)[1]', 'nvarchar(max)') "VIRTUAL_CMSAC"
--,a.XMLRECORD.value('data(/row/c139)[1]', 'nvarchar(max)') "LD_NO"
--,a.XMLRECORD.value('data(/row/c140)[1]', 'nvarchar(max)') "DISC_START_DATE"
--,a.XMLRECORD.value('data(/row/c141)[1]', 'nvarchar(max)') "DISC_END_DATE"
--,a.XMLRECORD.value('data(/row/c142)[1]', 'nvarchar(max)') "FEE_TYPE"
--,a.XMLRECORD.query('/row/c142') "FEE_TYPE_142"
--,a.XMLRECORD.value('data(/row/c143)[1]', 'nvarchar(max)') "FEE_PERC"
--,a.XMLRECORD.query('/row/c143') "FEE_PERC_143"
--,a.XMLRECORD.value('data(/row/c144)[1]', 'nvarchar(max)') "ORG_FEE_AMT"
--,a.XMLRECORD.query('/row/c144') "ORG_FEE_AMT_144"
--,a.XMLRECORD.value('data(/row/c145)[1]', 'nvarchar(max)') "FINAL_FEE_AMT"
--,a.XMLRECORD.query('/row/c145') "FINAL_FEE_AMT_145"
--,a.XMLRECORD.value('data(/row/c146)[1]', 'nvarchar(max)') "SAL_CRDTD"
--,a.XMLRECORD.value('data(/row/c147)[1]', 'nvarchar(max)') "BAB_SAL_TRF_Y_N"
--,a.XMLRECORD.value('data(/row/c148)[1]', 'nvarchar(max)') "NON_SAL_EMP_NAME"
--,a.XMLRECORD.value('data(/row/c149)[1]', 'nvarchar(max)') "NAFITH_STATUS"
--,a.XMLRECORD.value('data(/row/c150)[1]', 'nvarchar(max)') "NAFITH_REF_NUM"
--,a.XMLRECORD.value('data(/row/c151)[1]', 'nvarchar(max)') "DOC_CODE"
--,a.XMLRECORD.query('/row/c151') "DOC_CODE_151"
--,a.XMLRECORD.value('data(/row/c152)[1]', 'nvarchar(max)') "DOC_PATH"
--,a.XMLRECORD.query('/row/c152') "DOC_PATH_152"
--,a.XMLRECORD.value('data(/row/c153)[1]', 'nvarchar(max)') "DOC_STATUS"
--,a.XMLRECORD.query('/row/c153') "DOC_STATUS_153"
--,a.XMLRECORD.value('data(/row/c154)[1]', 'nvarchar(max)') "DOC_IMAGE"
--,a.XMLRECORD.query('/row/c154') "DOC_IMAGE_154"
--,a.XMLRECORD.value('data(/row/c155)[1]', 'nvarchar(max)') "CMDTY_TYPE"
--,a.XMLRECORD.value('data(/row/c156)[1]', 'nvarchar(max)') "CMDTY_COMP"
--,a.XMLRECORD.value('data(/row/c157)[1]', 'nvarchar(max)') "CMDTY_ID"
--,a.XMLRECORD.value('data(/row/c158)[1]', 'nvarchar(max)') "CMDTY_AMT"
--,a.XMLRECORD.value('data(/row/c159)[1]', 'nvarchar(max)') "CMDTY_ORDER_ID"
--,a.XMLRECORD.value('data(/row/c160)[1]', 'nvarchar(max)') "CMDTY_ORD_STATUS"
--,a.XMLRECORD.value('data(/row/c161)[1]', 'nvarchar(max)') "CMDTY_BUY_TXNREF"
--,a.XMLRECORD.value('data(/row/c162)[1]', 'nvarchar(max)') "CMDTY_SELL_TXNREF"
--,a.XMLRECORD.value('data(/row/c163)[1]', 'nvarchar(max)') "CMDTY_EXEC_AMT"
--,a.XMLRECORD.value('data(/row/c164)[1]', 'nvarchar(max)') "CMDTY_SALE_OR_DEL"
--,a.XMLRECORD.value('data(/row/c165)[1]', 'nvarchar(max)') "CMDTY_TRFR_STATUS"
--,a.XMLRECORD.value('data(/row/c166)[1]', 'nvarchar(max)') "CMDTY_SALE_ORD_STATUS"
--,a.XMLRECORD.value('data(/row/c167)[1]', 'nvarchar(max)') "ORDER_SEQ"
--,a.XMLRECORD.value('data(/row/c168)[1]', 'nvarchar(max)') "CMDTY_TRSFR_TXNREF"
--,a.XMLRECORD.value('data(/row/c169)[1]', 'nvarchar(max)') "DOMESTIC_LABOUR_NO"
--,a.XMLRECORD.value('data(/row/c170)[1]', 'nvarchar(max)') "EMPLOYED_FAMILY_NO"
--,a.XMLRECORD.value('data(/row/c171)[1]', 'nvarchar(max)') "AUTHENTICATION_TYPE"
--,a.XMLRECORD.value('data(/row/c172)[1]', 'nvarchar(max)') "FEE_DTLS"
--,a.XMLRECORD.query('/row/c172') "FEE_DTLS_172"
--,a.XMLRECORD.value('data(/row/c173)[1]', 'nvarchar(max)') "FEE_DESC_EN"
--,a.XMLRECORD.query('/row/c173') "FEE_DESC_EN_173"
--,a.XMLRECORD.value('data(/row/c174)[1]', 'nvarchar(max)') "FEE_DESC_AR"
--,a.XMLRECORD.query('/row/c174') "FEE_DESC_AR_174"
--,a.XMLRECORD.value('data(/row/c175)[1]', 'nvarchar(max)') "MONTHLY_PAYMENT_PERC"
--,a.XMLRECORD.value('data(/row/c176)[1]', 'nvarchar(max)') "CUST_AGREED_LIMIT"
--,a.XMLRECORD.value('data(/row/c177)[1]', 'nvarchar(max)') "DIGI_DOC_CODE"
--,a.XMLRECORD.query('/row/c177') "DIGI_DOC_CODE_177"
--,a.XMLRECORD.value('data(/row/c178)[1]', 'nvarchar(max)') "DIGI_DOC_PATH"
--,a.XMLRECORD.query('/row/c178') "DIGI_DOC_PATH_178"
--,a.XMLRECORD.value('data(/row/c179)[1]', 'nvarchar(max)') "RESERVED21"
--,a.XMLRECORD.value('data(/row/c180)[1]', 'nvarchar(max)') "RESERVED20"
--,a.XMLRECORD.value('data(/row/c181)[1]', 'nvarchar(max)') "RESERVED19"
--,a.XMLRECORD.value('data(/row/c182)[1]', 'nvarchar(max)') "RESERVED18"
--,a.XMLRECORD.value('data(/row/c183)[1]', 'nvarchar(max)') "RESERVED17"
--,a.XMLRECORD.value('data(/row/c184)[1]', 'nvarchar(max)') "RESERVED16"
--,a.XMLRECORD.value('data(/row/c185)[1]', 'nvarchar(max)') "RESERVED15"
--,a.XMLRECORD.value('data(/row/c186)[1]', 'nvarchar(max)') "RESERVED14"
--,a.XMLRECORD.value('data(/row/c187)[1]', 'nvarchar(max)') "RESERVED13"
--,a.XMLRECORD.value('data(/row/c188)[1]', 'nvarchar(max)') "RESERVED12"
--,a.XMLRECORD.value('data(/row/c189)[1]', 'nvarchar(max)') "RESERVED11"
--,a.XMLRECORD.value('data(/row/c190)[1]', 'nvarchar(max)') "RESERVED10"
--,a.XMLRECORD.value('data(/row/c191)[1]', 'nvarchar(max)') "RESERVED9"
--,a.XMLRECORD.value('data(/row/c192)[1]', 'nvarchar(max)') "RESERVED8"
--,a.XMLRECORD.value('data(/row/c193)[1]', 'nvarchar(max)') "RESERVED7"
--,a.XMLRECORD.value('data(/row/c194)[1]', 'nvarchar(max)') "RESERVED6"
--,a.XMLRECORD.value('data(/row/c195)[1]', 'nvarchar(max)') "RESERVED5"
--,a.XMLRECORD.value('data(/row/c196)[1]', 'nvarchar(max)') "RESERVED4"
--,a.XMLRECORD.value('data(/row/c197)[1]', 'nvarchar(max)') "RESERVED3"
--,a.XMLRECORD.value('data(/row/c198)[1]', 'nvarchar(max)') "RESERVED2"
--,a.XMLRECORD.value('data(/row/c199)[1]', 'nvarchar(max)') "RESERVED1"
--,a.XMLRECORD.value('data(/row/c200[not(@m)]/text())[1]', 'nvarchar(max)') "FIELDMV1"
--,a.XMLRECORD.query('/row/c200[@m="1" or not(@m)]') "FIELDMV1_200"
--,a.XMLRECORD.value('data(/row/c200[@m="2"]/text())[1]', 'nvarchar(max)') "FIELDMV2"
--,a.XMLRECORD.query('/row/c200[@m="2"]') "FIELDMV2_200"
--,a.XMLRECORD.value('data(/row/c200[@m="3"]/text())[1]', 'nvarchar(max)') "FIELDMV3"
--,a.XMLRECORD.query('/row/c200[@m="3"]') "FIELDMV3_200"
--,a.XMLRECORD.value('data(/row/c200[@m="4"]/text())[1]', 'nvarchar(max)') "FIELDMV4"
--,a.XMLRECORD.query('/row/c200[@m="4"]') "FIELDMV4_200"
--,a.XMLRECORD.value('data(/row/c200[@m="5"]/text())[1]', 'nvarchar(max)') "VERSION_NAME"
--,a.XMLRECORD.value('data(/row/c201)[1]', 'nvarchar(max)') "STMT_NO"
--,a.XMLRECORD.query('/row/c201') "STMT_NO_201"
--,a.XMLRECORD.value('data(/row/c202)[1]', 'nvarchar(max)') "OVERRIDE"
--,a.XMLRECORD.query('/row/c202') "OVERRIDE_202"
--,a.XMLRECORD.value('data(/row/c203)[1]', 'nvarchar(max)') "RECORD_STATUS"
--,a.XMLRECORD.value('data(/row/c204)[1]', 'nvarchar(max)') "CURR_NO"
--,a.XMLRECORD.value('data(/row/c205)[1]', 'nvarchar(max)') "INPUTTER"
--,a.XMLRECORD.query('/row/c205') "INPUTTER_205"
--,a.XMLRECORD.value('data(/row/c206)[1]', 'nvarchar(max)') "DATE_TIME"
--,a.XMLRECORD.query('/row/c206') "DATE_TIME_206"
--,a.XMLRECORD.value('data(/row/c207)[1]', 'nvarchar(max)') "AUTHORISER"
--,a.XMLRECORD.value('data(/row/c208)[1]', 'nvarchar(max)') "CO_CODE"
--,a.XMLRECORD.value('data(/row/c209)[1]', 'nvarchar(max)') "DEPT_CODE"
--,a.XMLRECORD.value('data(/row/c210)[1]', 'nvarchar(max)') "AUDITOR_CODE"
--,a.XMLRECORD.value('data(/row/c211)[1]', 'nvarchar(max)') "AUDIT_DATE_TIME"
FROM 
dbo.[FBNK_BAB_VISA_CRD_ISSUE] a
--where RECID in (
--'10165524',
--'10369757',
--'10412803',
--'10434128')
